name: Assigner
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  assignAuthor:
    name: Assign author
    uses: CumulusDS/workflows/.github/workflows/assign.yml@master
    secrets: inherit
